### ISSUE TITLE
Organize wt_data

### ISSUE THREAD

**Issue by dcmania** [NREL/wakebench_swift#3]
-Need to support more versions of FAST input files:  FASTv7, OpenFASTv1, OpenFASTv2, OpenFAST-Nalu, etc.   [See dcmania fork for an example with nalu.](https://github.com/dcmania/wakebench_swift/tree/master/wt_data/OpenFAST_V27)
-Add a readme.txt file to explain of of the different versions.
-Split the OpenFASTv1 and OpenFASTv2 versions into different folders.
-What does 'v1' refer to?

**Comment by ebranlard** [comment]
Hi David, 

- All the version you mention are now supported and we have added a new folder for the Nalu simulations (4636bb9) . For now, I haven't added the mesh and NALU input files though. 

- Readme files were added to explain the differences between the different folders.

- The OF1 and OF2 are so similar (the only difference being in the AeroDyn file) that I prefer keeping them alongside in a same folder, I find it easier to maintain, but I'm open to changing that.

- "v1" is version 1 of the wakebench turbine. All the simulation models in the subfolders of "v1" are based on the same turbine definition: same aero, same structure, same controller,etc. The models are made for different simulation tools (leading unfortunately to slightly different results). A version 2 will likely come in the future. This was clarified in the Readme files and on the [SWIFT website](https://wakebench-swift.readthedocs.io/en/latest/simulations.html#turbine-model)


Hopefully this will clarify things.
